CREATE TABLE Documents(ID INTEGER PRIMARY KEY, NAME TEXT UNIQUE);
CREATE TABLE Sentences(
    ID INTEGER PRIMARY KEY, DOCUMENT_ID INTEGER, SID INTEGER
);
CREATE TABLE Chunks(
    ID INTEGER PRIMARY KEY, DOCUMENT_ID INTEGER, SENTENCE_ID INTEGER,
    CID INTEGER, LINK INTEGER, HEAD INTEGER, FUNC INTEGER
);
CREATE TABLE Chunk_Tags(CHUNK INTEGER, NAME TEXT, VALUE TEXT);
CREATE TABLE Tokens(
    ID INTEGER PRIMARY KEY, DOCUMENT_ID INTEGER, SENTENCE_ID INTEGER, CHUNK_ID INTEGER,
    TID INTEGER, SURFACE TEXT, BASE TEXT, READ TEXT, PART TEXT, ATTR1 TEXT, ATTR2 TEXT,
    CONJ_TYPE TEXT, CONJ_FORM TEXT, NAMED_ENTITY TEXT, PAS_TYPE TEXT
);
CREATE TABLE Pas_Annotated(ID INTEGER PRIMARY_KEY, NAME TEXT UNIQUE);
CREATE TABLE Pth_Annotated(ID INTEGER PRIMARY_KEY, NAME TEXT UNIQUE);
CREATE TABLE Pth_Annotated_Sent(ID INTEGER PRIMARY_KEY);

CREATE TABLE Token_Tags(Token INTEGER, NAME TEXT, VALUE TEXT);
CREATE TABLE Coreference(ANAPHORA INTEGER UNIQUE, LINKTYPE TEXT, ANTECEDENT INTEGER);
CREATE TABLE PredicateTerm(PREDICATE INTEGER, CASEPT TEXT, LINKTYPE TEXT, ANTECEDENT INTEGER);
CREATE TABLE SemanticRole(PREDICATE INTEGER, SEMROLE TEXT, ANTECEDENT INTEGER);
CREATE TABLE VerbSemantic(PREDICATE INTEGER, SEMANTIC TEXT);
